print ("ofir's testing project is loading")
print ("hello world!")
input ("this program is going to ask you some questions, click enter to continue, otherwise close the window ")
name = input ("what is your name? ")
age = input ("what is your age? ")
email = input ("what is your email? ")
input("thank you for the info, click enter to continue to review your info")
print ("your name is ", name)
print ("\n your age is ", age)
print ("\n your email is ", email)